#!/usr/bin/env python3
# Copyright (c) 2026 Ian Adelman
# SPDX-License-Identifier: MIT
"""Emit host/tests/golden.h from the NumPy reference.

Run after any change to the quantizers, the container layout, or the reference
forward pass, and commit the result — CI regenerates it into a temp dir and
diffs, so a stale golden.h fails the build rather than silently weakening the
test.

    python3 tools/gen_golden.py --model build/test_q4.etq --out host/tests/golden.h
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__)))

from etq import reference  # noqa: E402
from etq.format import DTYPE_NAMES, Reader  # noqa: E402

# A fixed prompt-ish token walk. Ids 3.. are byte fallbacks in the toy vocab,
# so this exercises embeddings spread across the table rather than a clump.
TOKENS = [1, 40, 7, 300, 12, 259, 88, 2]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True)
    ap.add_argument("--q8-model", help="Q8_0 fixture; embeds golden_logits_q8 alongside")
    ap.add_argument("--out", required=True)
    args = ap.parse_args(argv)

    r = Reader(open(args.model, "rb").read())
    c = r.cfg
    logits = reference.generate_logits(args.model, TOKENS)

    logits_q8 = None
    if args.q8_model:
        c8 = Reader(open(args.q8_model, "rb").read()).cfg
        assert c8.vocab_size == c.vocab_size, "fixtures must share a vocab"
        assert c8.qtype != c.qtype, "--q8-model must differ in qtype from --model"
        logits_q8 = reference.generate_logits(args.q8_model, TOKENS)

    with open(args.out, "w") as f:
        f.write("/* Generated by tools/gen_golden.py -- do not edit.\n"
                " * Regenerate with: make -C host golden\n"
                " */\n#ifndef TQ_GOLDEN_H_\n#define TQ_GOLDEN_H_\n\n")
        f.write(f"/* model: {os.path.basename(args.model)}  "
                f"{DTYPE_NAMES[c.qtype]}  dim={c.dim} layers={c.n_layers} "
                f"heads={c.n_heads}/{c.n_kv_heads} vocab={c.vocab_size} */\n\n")
        f.write(f"#define GOLDEN_STEPS {len(TOKENS)}\n")
        f.write(f"#define GOLDEN_VOCAB {c.vocab_size}\n\n")
        f.write("static const int golden_tokens[GOLDEN_STEPS] = {")
        f.write(", ".join(str(t) for t in TOKENS))
        f.write("};\n\n")
        f.write("static const float golden_logits[GOLDEN_STEPS][GOLDEN_VOCAB] = {\n")
        for row in logits:
            f.write("\t{")
            f.write(", ".join(f"{v:.9g}f" for v in row))
            f.write("},\n")
        f.write("};\n")
        if logits_q8 is not None:
            f.write(
                "\n/* Same tokens, same source weights, quantized Q8_0. Q4 and Q8\n"
                " * logits legitimately diverge (different quantization error), so\n"
                " * the harness must compare each model against its own oracle. */\n"
            )
            f.write("static const float golden_logits_q8[GOLDEN_STEPS][GOLDEN_VOCAB] = {\n")
            for row in logits_q8:
                f.write("\t{")
                f.write(", ".join(f"{v:.9g}f" for v in row))
                f.write("},\n")
            f.write("};\n")
        f.write("\n#endif /* TQ_GOLDEN_H_ */\n")

    print(f"wrote {args.out}: {len(TOKENS)} steps x {c.vocab_size} logits",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
